---
- name: Update Webapp
  hosts: all
  become: "{{ lookup('env', 'BECOME') | default('true') | bool }}"
  tasks:
    - name: Install Git
      package:
        name: git
        state: present
      
    - name: Ensure the project directory exists
      file:
        path: "{{ item.path }}"
        state: directory
      loop: "{{ sites }}"

    - name: Clone or update the Git repository
      git:
        repo: "{{ lookup('env', 'GIT_REPO') }}"
        dest: "{{ item.path }}"
        key_file: "{{ lookup('env', 'SSH_KEY_FILE') }}"
        accept_hostkey: true
        version: "{{ lookup('env', 'GIT_BRANCH') }}"
        force: true
        update: yes
      loop: "{{ sites }}"

    - name: Set ownership of sites directory to www-data
      file:
        path: "{{ item.path }}"
        owner: www-data
        group: www-data
        recurse: yes
        state: directory
      loop: "{{ sites }}"


    - name: Execute commands
      shell: "{{ lookup('env', 'COMMAND_ENDING') }}"
      args:
        chdir: "{{ item.path }}"
      when: lookup('env', 'COMMAND_ENDING')|length > 0
      loop: "{{ sites }}"